name: "Despliegue de una imagen desde Docker Hub"

on:
  push:
    branches:
      - main

jobs:
    runs-container:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: ['3.10']
        steps:
            - name: Login dockerhub
              run: |
                echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
            - name: Pull image
              run: |
                    docker pull luisvega1981/python-app:latest
            - name: Run container
              run: |
                    docker run luisvega1981/python-app:latest    

        
        