name: Python application test with Github Actions

on: 
    push:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: ['3.10']

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                   python -m pip install  --upgrade pip
            - name: Run test
              run : |
                python test.py
            - name: Docker hub
              run: |
                echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin 
            # creacion de la imagen
            - name: Build image
              run: |
                docker build -t luisvega1981/python-app:latest .
            # push la imagen
            - name: Push image
              run: |
                docker push luisvega1981/python-app:latest
            - name: Deploy
              if: success()
              run: |
                echo "Deployed successfully"
            - name: Deploy failure
              if: failure()
              run: |
                 echo "Deploy failed"
        


